# Generated by Django 6.0.1 on 2026-01-15 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='card_kind',
            field=models.CharField(blank=True, choices=[('UZCARD', 'Uzcard'), ('HUMO', 'Humo'), ('VISA', 'Visa'), ('MC', 'Mastercard')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, choices=[('UZS', "So'm"), ('USD', 'Dollar'), ('EUR', 'Yevro'), ('RUB', 'Rubl')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.category'),
        ),
    ]
