# Generated by Django 6.0.1 on 2026-01-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_card_kind_account_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
