# Generated by Django 6.0.1 on 2026-01-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_account_bank_name_account_last4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(blank=True, choices=[('UZS', "So'm"), ('USD', 'Dollar')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CASH', 'Naqd pul'), ('CARD', 'Karta')], max_length=4),
        ),
    ]
