# Generated by Django 6.0.1 on 2026-01-15 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_account_currency_alter_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, choices=[('UZS', "So'm"), ('USD', 'Dollar')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='USD', max_length=3)),
                ('quote', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar')], default='UZS', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('base', 'quote', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_from', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_to', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='finance.account')),
                ('in_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_in', to='finance.transaction')),
                ('out_tx', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_out', to='finance.transaction')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='finance.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
